-- MySQL Script generated by MySQL Workbench
-- Wed May  9 13:32:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JOINTONS!!!!!!!!!!!
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JOINTONS!!!!!!!!!!!
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JOINTONS!!!!!!!!!!!` DEFAULT CHARACTER SET utf8 ;
USE `JOINTONS!!!!!!!!!!!` ;

-- -----------------------------------------------------
-- Table `JOINTONS!!!!!!!!!!!`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOINTONS!!!!!!!!!!!`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `U_Email` VARCHAR(45) NOT NULL,
  `U_Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOINTONS!!!!!!!!!!!`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOINTONS!!!!!!!!!!!`.`Articles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Content` VARCHAR(45) NOT NULL,
  `Picture` VARCHAR(45) NOT NULL,
  `date_publish` INT(8) NOT NULL,
  `id_users` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOINTONS!!!!!!!!!!!`.`Articles_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOINTONS!!!!!!!!!!!`.`Articles_has_Users` (
  `Articles_ID` INT NOT NULL,
  `Users_Id` INT NOT NULL,
  PRIMARY KEY (`Articles_ID`, `Users_Id`),
  INDEX `fk_Articles_has_Users_Users1_idx` (`Users_Id` ASC),
  INDEX `fk_Articles_has_Users_Articles_idx` (`Articles_ID` ASC),
  CONSTRAINT `fk_Articles_has_Users_Articles`
    FOREIGN KEY (`Articles_ID`)
    REFERENCES `JOINTONS!!!!!!!!!!!`.`Articles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Users_Users1`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `JOINTONS!!!!!!!!!!!`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
